@baseUrl = http://localhost:3000/api/users
@contentType = application/json

### Signup Operation
POST {{baseUrl}}/signup
Content-Type: {{contentType}}

{
    "email": "testuser4@example.com",
    "password": "TestPass123",
    "confirmPassword": "TestPass123"
}



### Login Operation
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "TestPass123"
}



