@baseUrl = http://localhost:3000/api/messages
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzZGI4YjE3Zi0wZTFhLTQ4Y2YtYWMwYi0xNTVhZDcxYzUyNTAiLCJpYXQiOjE3NDE5MTIxMDYsImV4cCI6MTc0MTkxMzAwNn0.gd5KwJ_yNGepu7e8f6OFQ1vqnxuOD6vMsKu1hIeK2o4
@sessionId = 4912ab84-e675-4dfd-b36a-8670bd5fb6c6

### Send Message (New Conversation)
POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "message": "Hello, how are you?",
    "sessionId": null
}

### Continue Conversation (Using Previous Session)
POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "message": "hey testing authentication requiremnts",
    "sessionId": "{{sessionId}}"
}

### Test Intent Detection
POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "message": "I need help with booking",
    "sessionId": null
}

### Test Error Handling
POST {{baseUrl}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
    "message": "",
    "sessionId": null
}

